### ISSUE TITLE
keyerror while executing Multitask training with disjoint datasets

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#1215]
## Steps to reproduce
Executed Multitask training with disjoint datasets as described at - https://pytext.readthedocs.io/en/master/disjoint_multitask_tutorial.html with pytext v0.3.0

## Observed Results
Observed following error at the test stage:
```
=== Starting testing...

        # for debug of GPU
        use_cuda_if_available: True
        device_id: 0
        world_size: 1
        torch.cuda.is_available(): True
        cuda.CUDA_ENABLED: True
        cuda.DISTRIBUTED_WORLD_SIZE: 1

Loading model from <mydir>/pytext/model.pt
Loaded checkpoint...
Use config saved in snapshot
Creating task: DocumentClassificationTask...
Skipped initializing tensorizers since they are loaded from a previously saved state.
Traceback (most recent call last):
  File "<mydir>/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp==0.2.3', 'console_scripts', 'pytext')()
  File "<mydir>/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<mydir>/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<mydir>/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<mydir>/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/pytext/main.py", line 402, in train
    metric_channels=metric_channels,
  File "<mydir>/lib/python3.6/site-packages/pytext/workflow.py", line 251, in test_model_from_snapshot_path
    test_results = task.test(data_source)
  File "<mydir>/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/pytext/task/new_task.py", line 213, in test
    self.metric_reporter,
  File "<mydir>/lib/python3.6/site-packages/pytext/utils/timing.py", line 215, in wrapper
    return fn(*args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/pytext/trainers/trainer.py", line 157, in test
    return self.run_epoch(state, test_iter, metric_reporter)
  File "<mydir>/lib/python3.6/site-packages/pytext/utils/timing.py", line 233, in wrapper
    result = fn(*args, **kwargs)
  File "<mydir>/lib/python3.6/site-packages/pytext/trainers/trainer.py", line 491, in run_epoch
    for sample in enumerate(data):
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 154, in pad_and_tensorize_batches
    for raw_batch, numberized_batch in batches:
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 137, in batchify
    for super_pool in self._group_iter(iterable, super_pool_size, None):
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 78, in _group_iter
    for group in itertools.zip_longest(*iterators):
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 309, in cache
    for numberized_row in numberized_rows:
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 297, in numberize_rows
    for name, tensorizer in self.tensorizers.items()
  File "<mydir>/lib/python3.6/site-packages/pytext/data/data.py", line 297, in <dictcomp>
    for name, tensorizer in self.tensorizers.items()
  File "<mydir>/lib/python3.6/site-packages/pytext/data/tensorizers.py", line 609, in numberize
    return self.vocab.lookup_all(row[self.label_column])
  File "<mydir>/lib/python3.6/site-packages/pytext/data/utils.py", line 135, in lookup_all
    res, unk_counter, total = self.lookup_all_internal(nested_values)
  File "<mydir>/lib/python3.6/site-packages/pytext/data/utils.py", line 176, in lookup_all_internal
    return lookup_value(nested_values)
  File "<mydir>/lib/python3.6/site-packages/pytext/data/utils.py", line 172, in lookup_value
    self.lookup_all_internal(value) if should_iter(value) else lookup(value)
  File "<mydir>/lib/python3.6/site-packages/pytext/data/utils.py", line 168, in lookup
    return self.idx[value], 0, 1
KeyError: 'sentence'
```

## Expected Results
The training should succeed.

**Comment by mwu1993** [comment]
can you share the final config for this run?
