### ISSUE TITLE
Error calling pytext from command line

### ISSUE THREAD

**Issue by moabaom** [facebookresearch/pytext#131]
I'm getting a syntax error at the very first step after installation of pytext. whether by calling pytext from command line or importing it in python shell I get the following error :

  $ pytext

```
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
Traceback (most recent call last):
  File "/home/ml/.virtualenvs/caffe2-pytext/bin/pytext", line 7, in <module>
    from pytext.main import main
  File "/home/ml/.virtualenvs/caffe2-pytext/lib/python3.5/site-packages/pytext/__init__.py", line 11, in <module>
    from .builtin_task import register_builtin_tasks
  File "/home/ml/.virtualenvs/caffe2-pytext/lib/python3.5/site-packages/pytext/builtin_task.py", line 4, in <module>
    from pytext.config.component import register_tasks
  File "/home/ml/.virtualenvs/caffe2-pytext/lib/python3.5/site-packages/pytext/config/__init__.py", line 4, in <module>
    from .pytext_config import ConfigBase, PyTextConfig, TestConfig  # noqa
  File "/home/ml/.virtualenvs/caffe2-pytext/lib/python3.5/site-packages/pytext/config/pytext_config.py", line 50
    raise TypeError(f"Failed to specify {unspecified_fields} for {type(self)}")
                                                                             ^
SyntaxError: invalid syntax
```

any hints as to whats the issue?

**Comment by m3rlin45** [comment]
What version of Python do you have installed? We require python 3.6+, as you can see here: https://pytext-pytext.readthedocs-hosted.com/en/latest/installation.html

We should restore the warning on the README though, I guess it got lost in the shuffle of document creation.

**Comment by snisarg** [comment]
Created https://github.com/facebookresearch/pytext/pull/132 to update README. 

@moabaom from your trace, I see that you're using python 3.5. Please try with 3.6 or 3.7. Reopen this issue in case you're still seeing this error.
