### ISSUE TITLE
Not able to run the pytext

### ISSUE THREAD

**Issue by fizerkhan** [facebookresearch/pytext#149]
I just follow the installation steps.

    python3.6 -m venv pytext_venv
    source pytext_venv/bin/activate
    pip3.6 install pytext-nlp

I am getting following error

```
(pytext_venv) root@ubuntu:~/test/pytext# pytext
Traceback (most recent call last):
  File "/root/test/pytext_venv/bin/pytext", line 7, in <module>
    from pytext.main import main
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/__init__.py", line 11, in <module>
    from .builtin_task import register_builtin_tasks
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/builtin_task.py", line 5, in <module>
    from pytext.task.disjoint_multitask import DisjointMultitask
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/task/__init__.py", line 4, in <module>
    from .serialize import load, save
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/task/serialize.py", line 12, in <module>
    from .task import create_task
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/task/task.py", line 25, in <module>
    from pytext.metric_reporters import MetricReporter
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/metric_reporters/__init__.py", line 6, in <module>
    from .compositional_metric_reporter import CompositionalMetricReporter
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/metric_reporters/compositional_metric_reporter.py", line 17, in <module>
    from pytext.metrics.intent_slot_metrics import (
  File "/root/test/pytext_venv/lib/python3.6/site-packages/pytext/metrics/intent_slot_metrics.py", line 6, in <module>
    from typing import Any, Counter, Dict, List, NamedTuple, Optional, Sequence, Set, Tuple
ImportError: cannot import name 'Counter'
```

I would like to see the help page of pytext.

How do I resolve it?

**Comment by snisarg** [comment]
This is a class from the standard library, see 
https://docs.python.org/3/library/typing.html#typing.Counter. It was introduced in Python 3.6.1. Can you use a newer version please.

**Comment by fizerkhan** [comment]
@snisarg Thanks. I am using Python 3.6.0. The docs says it works from Python 3.6 or above.

I have installed `Python 3.6.8rc1`. Now it works fine. The documentation has to be updated.
