### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'dtype'

### ISSUE THREAD

**Issue by hiepph** [facebookresearch/pytext#152]
I followed tutorial of ATIS on https://pytext-pytext.readthedocs-hosted.com/en/latest/atis_tutorial.html. On my way to step 3: `pytext train < sample_config.json` this error showed up:

```
Traceback (most recent call last):
  File "/home/hiepph/miniconda3/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp', 'console_scripts', 'pytext')()
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/hiepph/miniconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hiepph/src/pytext/pytext/main.py", line 232, in train
    train_model(config)
  File "/home/hiepph/src/pytext/pytext/workflow.py", line 55, in train_model
    task = prepare_task(config, dist_init_url, device_id, rank, world_size)
  File "/home/hiepph/src/pytext/pytext/workflow.py", line 78, in prepare_task
    return create_task(config.task)
  File "/home/hiepph/src/pytext/pytext/task/task.py", line 38, in create_task
    return create_component(ComponentType.TASK, task_config, metadata, model_state)
  File "/home/hiepph/src/pytext/pytext/config/component.py", line 142, in create_component
    return cls.from_config(config, *args, **kwargs)
  File "/home/hiepph/src/pytext/pytext/task/task.py", line 81, in from_config
    featurizer=featurizer,
  File "/home/hiepph/src/pytext/pytext/config/component.py", line 147, in create_data_handler
    ComponentType.DATA_HANDLER, data_handler_config, *args, **kwargs
  File "/home/hiepph/src/pytext/pytext/config/component.py", line 142, in create_component
    return cls.from_config(config, *args, **kwargs)
  File "/home/hiepph/src/pytext/pytext/data/joint_data_handler.py", line 76, in from_config
    DatasetFieldName.DOC_WEIGHT_FIELD: FloatField(),
  File "/home/hiepph/src/pytext/pytext/fields/field.py", line 288, in __init__
    unk_token=None,
  File "/home/hiepph/src/pytext/pytext/fields/field.py", line 54, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'dtype'
```

This doesn't happen with [Train your first model](https://pytext-pytext.readthedocs-hosted.com/en/latest/train_your_first_model.html) tutorial.

**Comment by snisarg** [comment]
This is the __init__() from torchtext.data.field: https://github.com/pytorch/text/blob/master/torchtext/data/field.py#L156, called from https://github.com/facebookresearch/pytext/blob/master/pytext/fields/field.py#L54

Are you using an older version of torchtext? Can you try updating it please.

**Comment by ZhuoranLyu** [comment]
@snisarg same error,  using pip install with version pytext-nlp==0.1.2

**Comment by snisarg** [comment]
@ZhuoranLyu what's the version of torchtext though? Try removing and adding that?

**Comment by ZhuoranLyu** [comment]
@snisarg Thanks, I fix this. I upgrade torchtext to the newest version.

**Comment by snisarg** [comment]
Did that solve the problem? Does it work now @ZhuoranLyu?

**Comment by ZhuoranLyu** [comment]
@snisarg Yes, it works fine. Thx!

**Comment by snisarg** [comment]
@hiepph can you try the same and let me know?

**Comment by hiepph** [comment]
Thanks @snisarg. Updating `torchtext` to the latest version fix the problem.

Will close the issue for now.
