### ISSUE TITLE
OSError: image not found when installing from source

### ISSUE THREAD

**Issue by erip** [facebookresearch/pytext#1663]
## Steps to reproduce

  1.  `git clone https://github.com/facebookresearch/pytext`
  2. `cd pytext`
  3. `python -m pip install .`
  4. `pytext`

## Observed Results

```log
WARNING:root:This caffe2 python run failed to load cuda module:No module named 'caffe2.python.caffe2_pybind11_state_gpu',and AMD hip module:No module named 'caffe2.python.caffe2_pybind11_state_hip'.Will run in CPU only mode.
Traceback (most recent call last):
  File "/Users/erippeth/miniconda3/envs/atis/bin/pytext", line 5, in <module>
    from pytext.main import main
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/__init__.py", line 12, in <module>
    from pytext.data.sources.data_source import DataSource
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/data/__init__.py", line 12, in <module>
    from .data import Batcher, Data, PoolingBatcher, generator_iterator
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/data/data.py", line 20, in <module>
    from .tensorizers import MetricTensorizer, Tensorizer, initialize_tensorizers
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/data/tensorizers.py", line 24, in <module>
    from pytext.data.tokenizers import Token, Tokenizer
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/data/tokenizers/__init__.py", line 4, in <module>
    from .tokenizer import (
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/data/tokenizers/tokenizer.py", line 13, in <module>
    from pytext.torchscript.tokenizer import ScriptDoNothingTokenizer, ScriptWordTokenizer
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/torchscript/tokenizer/__init__.py", line 4, in <module>
    from .bpe import ScriptBPE
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/torchscript/tokenizer/bpe.py", line 8, in <module>
    from pytext.torchscript.utils import utf8_chars
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/pytext/torchscript/utils.py", line 10, in <module>
    torch.ops.load_library("//caffe2/torch/fb/nlp/operators:padded_sequences")
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/Users/erippeth/miniconda3/envs/atis/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/caffe2/torch/fb/nlp/operators:padded_sequences, 6): image not found
```
## Expected Results

This should not explode. 😄

**Comment by 13293151871** [comment]
same here, any updates?
