### ISSUE TITLE
Dimension mismatch between representation layer and decoder layer

### ISSUE THREAD

**Issue by ZhuoranLyu** [facebookresearch/pytext#191]
## Steps to reproduce

  1.  pytext train < test.json
  2. test.json:
   ```
   "model": {
          "representation": {
            "BiLSTMSlotAttention": {
              "dropout": 0.1,
              "lstm": {
                "dropout": 0.1,
                "lstm_dim": 256,
                "num_layers": 2,
                "bidirectional": true
              },
              "slot_attention": {
                "attn_dimension": 64,
                "attention_type": "dot"
              }
            }
          },
          "decoder": {
            "hidden_dims": [256]
          },
          "output_layer": {
            "CRFOutputLayer": {}
          }
        },
```

## Observed Results
```
Rank 0 worker: Running epoch for Stage.TRAIN
Traceback (most recent call last):
  File "/home/lvzhuoran/anaconda3/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp-yckj', 'console_scripts', 'pytext')()
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/main.py", line 232, in train
    train_model(config)
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/workflow.py", line 57, in train_model
    trained_model, best_metric = task.train(config, rank, world_size)
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/task/task.py", line 157, in train
    rank=rank,
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/trainers/trainer.py", line 146, in train
    rank=rank,
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/trainers/trainer.py", line 216, in _run_epoch
    logits = model(*inputs)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/models/model.py", line 213, in forward
    *input_representation, *decoder_inputs
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/ssd/asr/lvzhuoran/project/nlp/pytext/pytext/models/decoders/mlp_decoder.py", line 54, in forward
    return self.mlp(torch.cat(input, 1))
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/lvzhuoran/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [3840 x 1024], m2: [512 x 256] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:266
```

## Expected Results

They should be the same size, [3840 x 1024] and [1024 x 256]

## Relevant Code

[https://github.com/facebookresearch/pytext/blob/fa0fea934bad76e9906c013e377ce80c77cbd5e4/pytext/models/representations/bilstm_slot_attn.py#L51](url)

I could open a pr to fix this.

**Comment by hikushalhere** [comment]
@ZhuoranLyu Please feel free to send us a PR for this.

**Comment by SwathiYanture** [comment]
Any resolution for this incidence? even we are facing the same issue.
Our config data is:
"model": {
          "representation": {
            "BiLSTMSlotAttention": {
              "lstm": {
                "dropout": 0,
                "lstm_dim": 366,
                "num_layers": 2,
                "bidirectional": true
              },
              "slot_attention":{
                "attention_type": "dot",
                "attn_dimension": 133
              }
            }
          },
          "output_layer": {
            "WordTaggingOutputLayer": {
              
            }
          }

The error is:
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/pytext/models/decoders/mlp_decoder.py", line 54, in forward
    return self.mlp(torch.cat(input, 1))
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/torch/nn/modules/container.py", line 92, in forward
    input = module(input)
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 67, in forward
    return F.linear(input, self.weight, self.bias)
  File "/datadrive/ner_poc/anaconda/lib/python3.6/site-packages/torch/nn/functional.py", line 1354, in linear
    output = input.matmul(weight.t())
RuntimeError: size mismatch, m1: [420 x 1464], m2: [732 x 6] at /pytorch/aten/src/TH/generic/THTensorMath.cpp:940

Any assistance would be appreciated.
Thanks

**Comment by SwathiYanture** [comment]
This issue is resolved on making the following change in the source code:

In bilstm_slot_attn.py changing  self.representation_dim: int = self.lstm.representation_dim to  self.representation_dim: int = word_representation_dim  resolved this issue.

The decoder dimension is set from representation_dim whose dimension is changed if slot attention sub-layer is included in the representation layer. 

Please correct if anything is wrong in changing the above code.
Thanks
