### ISSUE TITLE
docnn onnx export failure on ConstantFill 

### ISSUE THREAD

**Issue by WilliamTambellini** [facebookresearch/pytext#248]
## Steps to reproduce

  1. install fresh (2019 Jan 27) pytext : 
python3.6 -m venv pytext_venv
source pytext_venv/bin/activate
pip install pytext-nlp
  2. train docnn : 
pytext train < demo/configs/docnn.json
pytext export < demo/configs/docnn.json
  3. see error: Context: Bad node spec: input: "75" output: "76" op_type: "ConstantFill" attribute { name: "input_as_shape" i: 1 type: INT }

## Observed Results

...
Loading data...
load_path is not a config of embedding, skipping
save_path is not a config of embedding, skipping
freeze is not a config of embedding, skipping
shared_module_key is not a config of embedding, skipping
dict_feat is not a config of embedding, skipping
char_feat is not a config of embedding, skipping
pretrained_model_embedding is not a config of embedding, skipping
dense_feat is not a config of embedding, skipping
Model has 2 param groups (1 from embedding module) for optimizer
Saving caffe2 model to: /tmp/model.caffe2.predictor
Saving onnx model to: /tmp/model.onnx
/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/torch/nn/modules/module.py:487: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  result = self._slow_forward(*input, **kwargs)
Traceback (most recent call last):
  File "/home/wtambellini/repos/pytext/pytext_venv/bin/pytext", line 11, in <module>
    sys.exit(main())
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/pytext/main.py", line 303, in export
    export_saved_model_to_caffe2(model, output_path, output_onnx_path)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/pytext/workflow.py", line 130, in export_saved_model_to_caffe2
    task.export(task.model, export_caffe2_path, export_onnx_path=output_onnx_path)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/pytext/task/task.py", line 189, in export
    self.exporter.export_to_caffe2(model, export_path, export_onnx_path)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/pytext/exporters/exporter.py", line 192, in export_to_caffe2
    export_onnx_path,
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/pytext/utils/onnx_utils.py", line 50, in pytorch_to_caffe2
    onnx.checker.check_model(onnx_model)
  File "/home/wtambellini/repos/pytext/pytext_venv/lib64/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: No Op or Function registered for ConstantFill with domain_version of 9
==> Context: Bad node spec: input: "75" output: "76" op_type: "ConstantFill" attribute { name: "input_as_shape" i: 1 type: INT }

## Expected Results

successfull onnx export

## Relevant Code

pytext train < demo/configs/docnn.json
pytext export < demo/configs/docnn.json

## Note
The op ConstantFill op does not appear in the current doc : 
https://github.com/onnx/onnx/blob/master/docs/Operators.md
It was shown as experimental op on some reports. Has it been retired/removed ?

**Comment by WilliamTambellini** [comment]
A onnx model file has been generated in /tmp/
protoc --decode_raw < /tmp/model.onnx
2: "pytorch"
3: "0.4"
7 {
  1 {
    1: "embedding.0.word_embedding.weight"
    1: "tokens_vals"
    2: "15"
    4: "Gather"
 ...
[docnn.onnx.txt](https://github.com/facebookresearch/pytext/files/2801762/docnn.onnx.txt)

**Comment by WilliamTambellini** [comment]
The generated onnx file is openable through netron 
https://lutzroeder.github.io/netron/
and I indeed see 2 ContantFill ops, just after a Concat op and just before the LSTM cell.
Node prop:
input_as_shape : 1
inputs : id 75
outputs : id 76

**Comment by oneil512** [comment]
A work around for now is just to upgrade onnx to 1.4.1 while you are exporting.  I would guess if we fix the compatibility issues with the latest version of onnx and pytext then this issue would also be fixed as a result.

**Comment by WilliamTambellini** [comment]
Tks. Well, looks like 
pip install pytext-nlp
did install the latest onnx, meaning 1.4.1 : 
$ more pytext_venv/lib64/python3.6/site-packages/onnx/version.py 
# This file is generated by setup.py. DO NOT EDIT!
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals
version = '1.4.1'
git_version = '9e55ace55aad1ada27516038dfbdc66a8a0763db'

Did nt pytorch/pytext use it when exporting ?

**Comment by oneil512** [comment]
There is an open issue with the example code seg faulting from an incompatibility with onnx 1.4.1 and the solution was to downgrade to 1.3.0. I think the requirements.txt has onnx 1.3.0 now as well. But that seems to cause this problem.

**Comment by WilliamTambellini** [comment]
Hum, requirements.txt indeed requests onnx 1.3 : 
onnx==1.3.0
but 
pip install pytext-nlp
installed 1.4.1.
Tks.
