### ISSUE TITLE
pytext.config.serialize.ConfigParseError when training the example for hierarchical intent and slot filling

### ISSUE THREAD

**Issue by xtagon** [facebookresearch/pytext#262]
## Steps to reproduce

  1. Read the tutorial here: https://pytext-pytext.readthedocs-hosted.com/en/latest/hierarchical_intent_slot_tutorial.html
  2. Follow the steps up to and including `pytext train < demo/configs/rnng.json`

## Observed Results

  * An error is produced from the training command:

```
pytext train < demo/configs/rnng.json
No config file specified, reading from stdin
Traceback (most recent call last):
  File "/home/xtagon/software/pytext/pytext_venv/bin/pytext", line 11, in <module>
    sys.exit(main())
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/main.py", line 269, in train
    config = context.obj.load_config()
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/main.py", line 171, in load_config
    context.obj.config = parse_config(config)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 223, in parse_config
    return config_from_json(PyTextConfig, config_json["config"])
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 143, in config_from_json
    value = _value_from_json(f_cls, json_obj[field])
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 89, in _value_from_json
    return _union_from_json(cls.__args__, value)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 58, in _union_from_json
    return _value_from_json(subclass, json_obj[type_name])
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 87, in _value_from_json
    return config_from_json(cls, value)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 143, in config_from_json
    value = _value_from_json(f_cls, json_obj[field])
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 87, in _value_from_json
    return config_from_json(cls, value)
  File "/home/xtagon/software/pytext/pytext_venv/lib/python3.6/site-packages/pytext/config/serialize.py", line 131, in config_from_json
    detected in config json: {unknown_fields}"
pytext.config.serialize.ConfigParseError: Unknown fields for class OptimizerParams with fields {'lr', 'type', 'momentum', 'weight_decay'}             detected in config json: {'Adam'}
```

## Expected Results

  * I expected it to train the model

## Relevant Code

Here is a snipped from the rnng demo config from this repo, unmodified:

```
        "optimizer": {
          "Adam": {
            "lr": 0.0004,
            "weight_decay": 0.000004
          }
        },
```

## Workaround

I figured out that if you change that snipped to the following, the error no longer occurs:

```
        "optimizer": {
          "lr": 0.0004,
          "weight_decay": 0.000004
        },
```

Good enough for me, but I figured I'd report it. Thanks

**Comment by arbabu123** [comment]
Thank you @xtagon for figuring out the issue. We will send out a fix soon.

**Comment by arbabu123** [comment]
Feel free to reopen the issue if you still face it. Thanks.

**Comment by slowtokyo** [comment]
A similar issue came up with the `DocClassificationTask.Config` @ https://pytext-pytext.readthedocs-hosted.com/en/latest/configs/pytext.task.tasks.DocClassificationTask.Config.html

In the newest version of pytext it seems the default values for the trainer parameter needs to remove the random seed parameter and change from:
```
    "trainer": {
        "random_seed": 0,
        "epochs": 10,
        "early_stop_after": 0,
        "max_clip_norm": null,
        "report_train_metrics": true
    },
```
to
```
    "trainer": {
        "epochs": 10,
        "early_stop_after": 0,
        "max_clip_norm": null,
        "report_train_metrics": true
    },
```
