### ISSUE TITLE
Unable to export a model into caffe2

### ISSUE THREAD

**Issue by maya-ami** [facebookresearch/pytext#295]
## Steps to reproduce

  1. Follow the example "Execute your first model" in the documentation.
  2. Successfully trained the model. 
  3. But now unable to export the model to caffe2: when running `pytext export --output-path exported_model.c2 < demo/configs/docnn.json` the following errors arise:

## Observed Results
Traceback (most recent call last):
  File "/home/anaconda3/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp', 'console_scripts', 'pytext')()
  File "/home/anaconda3/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/anaconda3/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/anaconda3/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/anaconda3/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/anaconda3/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/Downloads/pytext-master/pytext/main.py", line 319, in export
    export_saved_model_to_caffe2(model, output_path, output_onnx_path)
  File "/home/Downloads/pytext-master/pytext/workflow.py", line 127, in export_saved_model_to_caffe2
    task.export(task.model, export_caffe2_path, export_onnx_path=output_onnx_path)
TypeError: export() missing 1 required positional argument: 'metric_channels'

## Expected Results

...[snip]
Saving caffe2 model to: exported_model.c2

Can't get what's wrong. Previously I could export models, but now missing a 'metric_channels' argument. What's that?

**Comment by puttkraidej** [comment]
I faced the same issue after updated to commit #da0d62749895319c9af9467dcac245b69dde7b29

**Comment by deepali-c** [comment]
I think this is resolved now by the PR- https://github.com/facebookresearch/pytext/pull/271

**Comment by Titousensei** [comment]
Looks resolved. Closing.
