### ISSUE TITLE
while exporting LM model pytext gives error :AttributeError: 'NoneType' object has no attribute 'export_output_names'

### ISSUE THREAD

**Issue by abb4s** [facebookresearch/pytext#412]
## Steps to reproduce
I want to create a language model by pytext trained on Shekspeare corpus
and make a simple test by generating some text with this model. so first I tried to export the model and then predict using exported model (I'm not sure this is the right way). 
  1.this is how my config file looks like :
`
{
    "task": {
        "LMTask": {
            "features": {
              "shared_module_key": "SHARED_EMBEDDING",
              "word_feat": {
                "vocab_file": "vocab.txt",
                "vocab_size": 2715,
                "vocab_from_train_data": false
              }
            },

            "data_handler": {
              "LanguageModelDataHandler": {
                "train_path": "shekspeare2.txt",
                "eval_path": "shekspeare2.txt",
                "test_path": "shekspeare2.txt",
                "train_batch_size": 16,
                "eval_batch_size": 16,
                "test_batch_size": 16
              }
            },
            "exporter":{},
            "trainer": {
              "epochs": 1
            },
            "model": {
              "representation": {
                "shared_module_key": "SHARED_LSTM"
              },
              "decoder": {
                "hidden_dims": [
                  10
                ]
              }
            }
            
          }
    }
  }`
3.and the export command : "$bin/pytext export --output-path mymodel.c2 < lm.config"

## Observed Results
the error : 

> AttributeError: 'NoneType' object has no attribute 'export_output_names'

```
Traceback (most recent call last):
  File "bin/pytext", line 10, in <module>
    sys.exit(main())
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/main.py", line 319, in export
    export_saved_model_to_caffe2(model, output_path, output_onnx_path)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/workflow.py", line 128, in export_saved_model_to_caffe2
    task.data_handler.metadata,
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/config/component.py", line 178, in create_exporter
    return create_component(ComponentType.EXPORTER, exporter_config, *args, **kwargs)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/config/component.py", line 144, in create_component
    return cls.from_config(config, *args, **kwargs)
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/exporters/exporter.py", line 66, in from_config
    name for target in target_config for name in target.export_output_names
  File "/media/abbas/D/workspace/NLP/lib/python3.6/site-packages/pytext/exporters/exporter.py", line 66, in <listcomp>
    name for target in target_config for name in target.export_output_names
AttributeError: 'NoneType' object has no attribute 'export_output_names'
```

**Comment by abb4s** [comment]
(Facebook is in Holiday !) please some one correct me!

**Comment by jingfeidu** [comment]
Hi @abb4s, could you add labels in your config and try to export it again? For example,
`
{
"task": {
"LMTask": {
"features": {
"shared_module_key": "SHARED_EMBEDDING",
"word_feat": {
"vocab_file": "vocab.txt",
"vocab_size": 2715,
"vocab_from_train_data": false
}
},

**"labels": {},**

        "data_handler": {
          "LanguageModelDataHandler": {
            "train_path": "shekspeare2.txt",
            "eval_path": "shekspeare2.txt",
            "test_path": "shekspeare2.txt",
            "train_batch_size": 16,
            "eval_batch_size": 16,
            "test_batch_size": 16
          }
        },
        "exporter":{},
        "trainer": {
          "epochs": 1
        },
        "model": {
          "representation": {
            "shared_module_key": "SHARED_LSTM"
          },
          "decoder": {
            "hidden_dims": [
              10
            ]
          }
        }
        
      }
}
}`

**Comment by abb4s** [comment]
thanks @jingfeidu. the error removed but when I run predict commend like this : 
`pytext --config-file lmlstm.2.json  predict --exported-model lmlstm.2.c2 <<< '{"raw_text": "the"}'`
the output is : 
`Install apex from https://github.com/NVIDIA/apex/.
Loading model from lmlstm.2.c2
Model loaded, reading example JSON from stdin
{}`
the output is empty. I need to generate text but it dosen't give any information for do that. 
How can I generate a random text by language model trained by pytext ?

**Comment by puttkraidej** [comment]
I faced the same error, even if I added "labels": {} in config file :(
