### ISSUE TITLE
NER demo does not work after add one token

### ISSUE THREAD

**Issue by jianwolf** [facebookresearch/pytext#553]
## Steps to reproduce

This is the config file.
```{
  "task": {
    "NewWordTaggingTask": {
      "data": {
        "source": {
          "TSVDataSource": {
            "field_names": ["slots", "text"],
            "train_filename": "test_ner.tsv",
            "test_filename": "test_ner.tsv",
            "eval_filename": "test_ner.tsv"
          }
        }
      }
    }
  }
}
```

If the test_ner.tsv is a one liner:
`10:22:datetime,28:56:reminder/todo	remind me Monday night that get doe with work 12 Tuesday	`, then the config can work
But if I add another token, like:
`10:22:datetime,28:56:reminder/todo	remind me Monday night that get doe with work 12 Tuesday Tuesday	`

Then got ```Traceback (most recent call last):
  File "/liveperson/code/p3env/bin/pytext", line 10, in <module>
    sys.exit(main())
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/main.py", line 317, in train
    train_model(config, metric_channels=metric_channels)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/workflow.py", line 83, in train_model
    trained_model, best_metric = task.train(config, rank, world_size, dist_init_url)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/task/new_task.py", line 184, in train
    rank=rank,
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/utils/timing.py", line 164, in wrapper
    return fn(*args, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/trainers/trainer.py", line 287, in train
    self.run_epoch(state, training_data, metric_reporter)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/utils/timing.py", line 164, in wrapper
    return fn(*args, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/task/new_task.py", line 41, in run_epoch
    loss, metric_data = model.train_batch(batch)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/models/model.py", line 152, in train_batch
    loss = self.get_loss(model_outputs, targets, None)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/models/model.py", line 85, in get_loss
    return self.output_layer.get_loss(logit, target, context)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/models/output_layers/word_tagging_output_layer.py", line 67, in get_loss
    return self.loss_fn(logit.view(-1, logit.size()[-1]), target.view(-1), reduce)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/pytext/loss/loss.py", line 35, in __call__
    weight=self.weight,
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/functional.py", line 1788, in nll_loss
    .format(input.size(0), target.size(0)))
ValueError: Expected input batch_size (12) to match target batch_size (11).```

But why? It's just one more token...

**Comment by Yuhuishishishi** [comment]
Yes, I am encountering the same problem. Did you find a way to resolve this @jianwolf ?

**Comment by jianwolf** [comment]
@Yuhuishishishi No I didn't... Could you let me know if you find a way? Thanks!

**Comment by Titousensei** [comment]
I can't reproduce the issue with "WordTaggingTask", which is "NewWordTaggingTask" renamed in the last version. What command did you run? Was it `pytext train < ner.json`? Is the issue still happening to you?
