### ISSUE TITLE
'DocumentClassificationTask' object has no attribute 'exporter'

### ISSUE THREAD

**Issue by megupta** [facebookresearch/pytext#641]
## Steps to reproduce

1. Fresh install of Ubuntu 17.04
2. Install essential libraries; python 3.6.7
3. Install CUDA 10.0
4. Install torch 
5. Install apex
6. Install pytext via source (includes onnx 1.5.0)
7. Trying example: train, test, export

## Observed Results
Export fails

:pytext export < demo/configs/docnn.json
No config file specified, reading from stdin
Exporting /tmp/model.pt to caffe2 file: /tmp/model.caffe2.predictor and onnx file: /tmp/model.onnx
Loading model from /tmp/model.pt...
Traceback (most recent call last):
  File "/home/dave/apex/pytext_venv/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp', 'console_scripts', 'pytext')()
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dave/pytext/pytext/main.py", line 358, in export
    export_saved_model_to_caffe2(model, output_path, output_onnx_path)
  File "/home/dave/pytext/pytext/workflow.py", line 161, in export_saved_model_to_caffe2
    if task.exporter is None:
AttributeError: 'DocumentClassificationTask' object has no attribute 'exporter'

Downgrading onnx to 1.4.1, same error.

Downgrading onnx to 1.3.0 breaks train

:pytext train < demo/configs/docnn.json
Saving onnx model to: /tmp/model.onnx
Traceback (most recent call last):
  File "/home/dave/apex/pytext_venv/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp', 'console_scripts', 'pytext')()
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dave/pytext/pytext/main.py", line 328, in train
    train_model(config, metric_channels=metric_channels)
  File "/home/dave/pytext/pytext/workflow.py", line 99, in train_model
    save_and_export(config, task, metric_channels)
  File "/home/dave/pytext/pytext/workflow.py", line 151, in save_and_export
    config.export_onnx_path,
  File "/home/dave/pytext/pytext/task/new_task.py", line 160, in export
    self.data.tensorizers, batch, export_path, export_onnx_path=export_onnx_path
  File "/home/dave/pytext/pytext/models/doc_model.py", line 112, in caffe2_export
    return exporter.export_to_caffe2(self, path, export_onnx_path=export_onnx_path)
  File "/home/dave/pytext/pytext/exporters/exporter.py", line 182, in export_to_caffe2
    export_onnx_path,
  File "/home/dave/pytext/pytext/utils/onnx.py", line 52, in pytorch_to_caffe2
    onnx.checker.check_model(onnx_model)
  File "/home/dave/apex/pytext_venv/lib/python3.6/site-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.

## Expected Results

Export to succeed. Over the past week I've tried this with various versions of CUDA, Torch, python, and flavors of Linux with various issues. I've also read through the documentation/tickets and haven't found any of the issues mentioned so I'm going to start reporting them

**Comment by seayoung1112** [comment]
@Titousensei could you take a look?

**Comment by Titousensei** [comment]
I think this is resolved. (It works for me on a fresh install from source.) @megupta can you confirm?

**Comment by megupta** [comment]
This is fixed with latest release.
