### ISSUE TITLE
created_predictor API in python wrapper has not been updated to align with pytext-nlp==0.2.0, AttributeError: 'DocumentClassificationTask.Config' object has no attribute 'features'

### ISSUE THREAD

**Issue by puttkraidej** [facebookresearch/pytext#701]
## Steps to reproduce

  1. pytext-nlp==0.2.0 (python > 3.6)
  2. both gpu and cpu setting
  

## Observed Results

  * I faced this error msg, while I tried to follow the same instruction in python shell
$pytext.create_predictor(config, model_filepath)

AttributeError: 'DocumentClassificationTask.Config' object has no attribute 'features'

## What did you expect to happen?

I expected model to be created via this method (api) as it was in previous version.

**Comment by Meai1** [comment]
just tried it with the latest from github:

```
(pytext_venv) pc@debian:~/workarea/experiments/pytext$ pytext export < pytext/demo/configs/docnn.json
Install apex from https://github.com/NVIDIA/apex/.
No config file specified, reading from stdin
Exporting /tmp/model.pt to caffe2 file: /tmp/model.caffe2.predictor and onnx file: /tmp/model.onnx
Loading model from /tmp/model.pt...
Saving caffe2 model to: /tmp/model.caffe2.predictor
Saving onnx model to: /tmp/model.onnx
Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.Warning: ATen was a removed  experimental ops. In the future, we may directly reject this operator. Please update your model as soon as possible.(pytext_venv) pc@debian:~/workarea/experiments/pytext$ pytext --config-file demo/configs/docnn.json predict <<< '{"raw_text": "c^Cate an alarm for 1:30 pm"}'

(pytext_venv) pc@debian:~/workarea/experiments/pytext$ pytext --config-file pytext/demo/configs/docnn.json predict <<< '{"raw_text": "create an alarm for 1:30 pm"}'
Install apex from https://github.com/NVIDIA/apex/.
Loading model from /tmp/model.caffe2.predictor
Traceback (most recent call last):
  File "/home/pc/workarea/experiments/pytext/pytext_venv/bin/pytext", line 10, in <module>
    sys.exit(main())
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/pytext/main.py", line 381, in predict
    predictor = create_predictor(config, exported_model)
  File "/home/pc/workarea/experiments/pytext/pytext_venv/lib/python3.7/site-packages/pytext/__init__.py", line 85, in create_predictor
    feature_config = task.features
AttributeError: 'DocumentClassificationTask.Config' object has no attribute 'features'
```

**Comment by r-wheeler** [comment]
Just ran into the same issue..

**Comment by fantasy** [comment]
Ran into the same issue too.

**Comment by deepali-c** [comment]
Even I ran into this issue.

**Comment by deepali-c** [comment]
Appears related to https://github.com/facebookresearch/pytext/issues/641

**Comment by rhubain** [comment]
Same issue too

**Comment by Titousensei** [comment]
Issue is fixed in source. Will be in upcoming release v0.2.1. Closing.
