### ISSUE TITLE
Issues observed with Custom Data Format example

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#774]
## Steps to reproduce
Follow the steps at - https://pytext.readthedocs.io/en/stable/datasource_tutorial.html#

## Observed Results
1. `AttributeError: 'AtisIntentDataSource' object has no attribute 'intent'`
```
$ python3 my_classifier/source.py atis | head -n 3
Install apex from https://github.com/NVIDIA/apex/.
Traceback (most recent call last):
  File "my_classifier/source.py", line 154, in <module>
    for row in src.raw_train_data_generator():
  File "my_classifier/source.py", line 127, in raw_train_data_generator
    intent_reader=reader(self.train_intent_filepath, self.intent),
AttributeError: 'AtisIntentDataSource' object has no attribute 'intent'
```
A solution for this is available at https://github.com/facebookresearch/pytext/pull/564

2. Next observed the following error:
```
$ python3 my_classifier/source.py atis | head -n 3
Install apex from https://github.com/NVIDIA/apex/.
TRAIN {'query': 'i want to fly from boston at 838 am and arrive in denver at 1110 in the morning', 'intent': ''}
TRAIN {'query': 'what is the arrival time in san francisco for the 755 am flight leaving washington', 'intent': ''}
TRAIN {'query': 'cheapest airfare from tacoma to orlando', 'intent': ''}
Traceback (most recent call last):
  File "my_classifier/source.py", line 155, in <module>
    print("TRAIN", row)
BrokenPipeError: [Errno 32] Broken pipe
```
I resolved by handling `BrokenPipeError` in `my_classifier/source.py` 

3. Next step - `ModuleNotFoundError: No module named 'my_classifier'`
```
$  pytext --include my_classifier gen-default-config AtisIntentDataSource DocumentClassificationTask > my_classifier/config.json
Install apex from https://github.com/NVIDIA/apex/.
Including: my_classifier
... importing module: my_classifier.source
Traceback (most recent call last):
  File "<mydir>/envs/pytext020/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp==0.2.0', 'console_scripts', 'pytext')()
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 1134, in invoke
    Command.invoke(self, ctx)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/pytext/main.py", line 203, in main
    add_include(path)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/pytext/builtin_task.py", line 53, in add_include
    my_module = importlib.import_module(mod_path)
  File "<mydir>/envs/pytext020/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'my_classifier'
```

4.  I resolved #3 above then, observed the following error:
```
$ pytext --include my_classifier gen-default-config AtisIntentDataSource DocumentClassificationTask
Install apex from https://github.com/NVIDIA/apex/.
Including: my_classifier
['<mydir>envs/pytext020/bin', '<mydir>/envs/pytext020/lib/python36.zip', '<mydir>/envs/pytext020/lib/python3.6', '<mydir>/envs/pytext020/lib/python3.6/lib-dynload', '<mydir>/envs/pytext020/lib/python3.6/site-packages', '']
... importing module: my_classifier.source
... importing: <class 'my_classifier.source.AtisIntentDataSource'>
<mydir>/envs/pytext020/lib/python3.6/site-packages/torch/distributed/distributed_c10d.py:107: UserWarning: torch.distributed.reduce_op is deprecated, please use torch.distributed.ReduceOp instead
  warnings.warn("torch.distributed.reduce_op is deprecated, please use "
Traceback (most recent call last):
  File "<mydir>/envs/pytext020/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp==0.2.0', 'console_scripts', 'pytext')()
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/pytext/main.py", line 256, in gen_default_config
    cfg = gen_config_impl(task_name, options)
  File "<mydir>/envs/pytext020/lib/python3.6/site-packages/pytext/main.py", line 153, in gen_config_impl
    raise Exception(f"Unknown option: {opt}")
Exception: Unknown option: DocumentClassificationTask
```

  * What happened?  This could be a description, log output, etc.
## Expected Results
Custom Data format example is expected to succeed.

**Comment by Titousensei** [comment]
Thanks for the feedback.
- as you observed, issue 1 is already solved.
- for issue 2, BrokenPipeError is often caused by truncated files. Handling it as an exception might hide the fact that your files are corrupted. Could you verify that yours are complete? Mine have 4978 rows for train and 893 for test.
- how did you resolve issue 3? --include my_classifier tells PyText to look into the directory my_classifier/ for your custom python files. Knowing the problem you had and how you resolved it will help me print a better error message.
- issue 4 is a known problem and the updated tutorial should be published soon. In the mean time, you just need to revert the two arguments:
  $ pytext --include my_classifier gen-default-config DocumentClassificationTask AtisIntentDataSource

**Comment by deepali-c** [comment]
@Titousensei, I had resolved three above by adding the following in `add_include` method in `builtin_task.py`

```
    import sys
    sys.path.append('')

```

**Comment by deepali-c** [comment]
I tried this with `v0.2.2` and observed the following:
#1 is resolved
#2 is now observed as:
 ```
python3 my_classifier/source.py atis | head -n 3
WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
Install apex from https://github.com/NVIDIA/apex/.
TRAIN {'query': 'i want to fly from boston at 838 am and arrive in denver at 1110 in the morning', 'intent': ''}
TRAIN {'query': 'what is the arrival time in san francisco for the 755 am flight leaving washington', 'intent': ''}
TRAIN {'query': 'cheapest airfare from tacoma to orlando', 'intent': ''}
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
BrokenPipeError: [Errno 32] Broken pipe
```
#3 is still seen and I changed `builtin_task.py` to get it to work. 
#4 is not seen, training is successful.

**Comment by sai-prasanna** [comment]
> @Titousensei, I had resolved three above by adding the following in `add_include` method in `builtin_task.py`
> 
> ```
>     import sys
>     sys.path.append('')
> ```

@Titousensei  Can I give a merge request for this? Or is there a better way to do this? 
I am getting the same error, which is resolved by adding current dir to sys path.
