### ISSUE TITLE
TypeError while executing atis tutorial

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#919]
## Steps to reproduce

Followed the steps at https://pytext.readthedocs.io/en/master/atis_tutorial.html with `pytext v0.2.2`.

## Observed Results
```
$ pytext train < sample_config.json
Install apex from https://github.com/NVIDIA/apex/.
No config file specified, reading from stdin
WARNING - Applying old config adapter for version=0. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=1. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=2. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=3. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=4. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=5. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=6. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=7. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=8. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=9. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=10. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=11. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=12. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=13. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=14. Please consider migrating your old configs to the latest version.

===Starting training...

Parameters: PyTextConfig:
    debug_path: <mydir>/pytext/model.debug
    distributed_world_size: 1
    export_caffe2_path: <mydir>/pytext/model.caffe2.predictor
    export_onnx_path: <mydir>/pytext/model.onnx
    export_torchscript_path: None
    load_snapshot_path:
    modules_save_dir:
    random_seed: None
    report_eval_results: False
    save_all_checkpoints: False
    save_module_checkpoints: False
    save_snapshot_path: <mydir>/pytext/model.pt
    task: IntentSlotTask.Config:
        data: Data.Config:
            batcher: PoolingBatcher.Config:
                eval_batch_size: 128
                pool_num_batches: 10000
                test_batch_size: 128
                train_batch_size: 128
            in_memory: True
            sort_key: tokens
            source: TSVDataSource.Config:
                column_mapping: {}
                delimiter:
                eval_filename: demo/atis_joint_model/atis.processed.val.csv
                field_names: ['label', 'slots', 'text', 'doc_weight', 'word_weight']
                quoted: False
                test_filename: demo/atis_joint_model/atis.processed.test.csv
                train_filename: demo/atis_joint_model/atis.processed.train.csv
        metric_reporter: IntentSlotMetricReporter.Config:
            output_path: <mydir>/pytext/test_out.txt
            pep_format: False
        model: IntentSlotModel.Config:
            decoder: IntentSlotModelDecoder.Config:
                doc_decoder: MLPDecoder.Config:
                    activation: Activation.RELU
                    dropout: 0.0
                    freeze: False
                    hidden_dims: []
                    layer_norm: False
                    load_path: None
                    out_dim: None
                    save_path: None
                    shared_module_key: None
                freeze: False
                load_path: None
                save_path: None
                shared_module_key: None
                use_doc_probs_in_word: False
                word_decoder: MLPDecoder.Config:
                    activation: Activation.RELU
                    dropout: 0.0
                    freeze: False
                    hidden_dims: []
                    layer_norm: False
                    load_path: None
                    out_dim: None
                    save_path: None
                    shared_module_key: None
            default_doc_loss_weight: 0.2
            default_word_loss_weight: 0.5
            inputs: ModelInput:
                doc_labels: LabelTensorizer.Config:
                    allow_unknown: True
                    column: label
                    label_vocab: None
                    pad_in_vocab: False
                doc_weight: FloatTensorizer.Config:
                    column: doc_weight
                tokens: TokenTensorizer.Config:
                    add_bos_token: False
                    add_eos_token: False
                    column: text
                    max_seq_len: None
                    tokenizer: Tokenizer.Config:
                        lowercase: True
                        split_regex: \s+
                    use_eos_token_for_bos: False
                    vocab: VocabConfig:
                        build_from_data: True
                        size_from_data: 0
                        vocab_files: []
                word_labels: SlotLabelTensorizer.Config:
                    allow_unknown: True
                    slot_column: slots
                    text_column: text
                    tokenizer: Tokenizer.Config:
                        lowercase: True
                        split_regex: \s+
                word_weight: FloatTensorizer.Config:
                    column: word_weight
            output_layer: IntentSlotOutputLayer.Config:
                doc_output: ClassificationOutputLayer.Config:
                    freeze: False
                    label_weights: None
                    load_path: None
                    loss: CrossEntropyLoss.Config:
                    save_path: None
                    shared_module_key: None
                freeze: False
                load_path: None
                save_path: None
                shared_module_key: None
                word_output: CRFOutputLayer.Config:
                    freeze: False
                    load_path: None
                    save_path: None
                    shared_module_key: None
            representation: BiLSTMDocSlotAttention.Config:
                doc_mlp_layers: 0
                dropout: 0.4
                freeze: False
                load_path: None
                lstm: BiLSTM.Config:
                    bidirectional: True
                    dropout: 0.4
                    freeze: False
                    load_path: None
                    lstm_dim: 32
                    num_layers: 1
                    pack_sequence: True
                    save_path: None
                    shared_module_key: None
                pooling: SelfAttention.Config:
                    attn_dimension: 64
                    dropout: 0.4
                save_path: None
                shared_module_key: None
                slot_attention: None
                word_mlp_layers: 0
            word_embedding: WordEmbedding.Config:
                embed_dim: 100
                embedding_init_range: None
                embedding_init_strategy: EmbedInitStrategy.RANDOM
                export_input_names: ['tokens_vals']
                freeze: False
                load_path: None
                lowercase_tokens: True
                min_freq: 1
                mlp_layer_dims: []
                padding_idx: None
                pretrained_embeddings_path: demo/atis_joint_model/glove.6B.100d.txt
                save_path: None
                shared_module_key: None
                vocab_file:
                vocab_from_all_data: False
                vocab_from_pretrained_embeddings: False
                vocab_from_train_data: True
                vocab_size: 0
        trainer: TaskTrainer.Config:
            do_eval: True
            early_stop_after: 0
            epochs: 20
            max_clip_norm: None
            num_accumulated_batches: 1
            num_batches_per_epoch: None
            num_samples_to_log_progress: 1000
            optimizer: Adam.Config:
                eps: 1e-08
                lr: 0.001
                weight_decay: 1e-05
            report_train_metrics: True
            scheduler: None
            sparsifier: None
            target_time_limit_seconds: None
    test_out_path: <mydir>/pytext/test_out.txt
    torchscript_quantize: False
    use_cuda_if_available: True
    use_deterministic_cudnn: False
    use_fp16: False
    use_tensorboard: True
    version: 15


    # for debug of GPU
    use_cuda_if_available: True
    device_id: 0
    world_size: 1
    torch.cuda.is_available(): True
    cuda.CUDA_ENABLED: True
    cuda.DISTRIBUTED_WORLD_SIZE: 1

# for debug of FP16: fp16_enabled=False
Traceback (most recent call last):
  File "<myenv>/lib/python3.6/site-packages/pytext/config/component.py", line 154, in create_component
    return cls.from_config(config, *args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/pytext/data/data.py", line 243, in from_config
    **kwargs,
  File "<myenv>/lib/python3.6/site-packages/pytext/data/data.py", line 270, in __init__
    initialize_tensorizers(self.tensorizers, full_train_data)
  File "<myenv>/lib/python3.6/site-packages/pytext/data/tensorizers.py", line 1306, in initialize_tensorizers
    for row in data_source:
  File "<myenv>/lib/python3.6/site-packages/pytext/data/sources/data_source.py", line 227, in _convert_raw_source
    example = self._read_example(row)
  File "<myenv>/lib/python3.6/site-packages/pytext/data/sources/data_source.py", line 207, in _read_example
    example[name] = self.load(value, self.schema[name])
  File "<myenv>/lib/python3.6/site-packages/pytext/data/sources/data_source.py", line 248, in load
    return converter(value)
  File "<myenv>/lib/python3.6/site-packages/pytext/data/sources/data_source.py", line 348, in load_float
    return float(f)
TypeError: float() argument must be a string or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<myenv>/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp==0.2.2', 'console_scripts', 'pytext')()
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/pytext/main.py", line 379, in train
    train_model(config, metric_channels=metric_channels)
  File "<myenv>/lib/python3.6/site-packages/pytext/workflow.py", line 89, in train_model
    config, dist_init_url, device_id, rank, world_size, metric_channels, metadata
  File "<myenv>/lib/python3.6/site-packages/pytext/workflow.py", line 125, in prepare_task
    config.task, metadata=metadata, rank=rank, world_size=world_size
  File "<myenv>/lib/python3.6/site-packages/pytext/task/task.py", line 43, in create_task
    world_size=world_size,
  File "<myenv>/lib/python3.6/site-packages/pytext/config/component.py", line 154, in create_component
    return cls.from_config(config, *args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/pytext/task/new_task.py", line 100, in from_config
    tensorizers, data = cls._init_tensorizers(config, tensorizers, rank, world_size)
  File "<myenv>/lib/python3.6/site-packages/pytext/task/new_task.py", line 143, in _init_tensorizers
    init_tensorizers=init_tensorizers,
  File "<myenv>/lib/python3.6/site-packages/pytext/config/component.py", line 156, in create_component
    raise Exception(f"Can't create component {cls}: {str(e)}")
Exception: Can't create component <class 'pytext.data.data.Data'>: float() argument must be a string or a number, not 'NoneType'
```

## Expected Results
The training should succeed.

**Comment by deepali-c** [comment]
This has been fixed by the following PR on master branch - https://github.com/facebookresearch/pytext/pull/915. 

applying this patch to `v0.2.2` leads to the following issue at predict:

```$ pytext --config-file demo/atis_joint_model/atis_joint_config.json   predict --exported-model /tmp/atis_joint_model.c2 <<< '{"raw_text": "flights from colorado"}'
Install apex from https://github.com/NVIDIA/apex/.
WARNING - Applying old config adapter for version=0. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=1. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=2. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=3. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=4. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=5. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=6. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=7. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=8. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=9. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=10. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=11. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=12. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=13. Please consider migrating your old configs to the latest version.
WARNING - Applying old config adapter for version=14. Please consider migrating your old configs to the latest version.
Loading model from /tmp/atis_joint_model.c2
Model loaded, reading example JSON from stdin
Traceback (most recent call last):
  File "<myenv>/bin/pytext", line 11, in <module>
    load_entry_point('pytext-nlp==0.2.2', 'console_scripts', 'pytext')()
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "<myenv>/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "<myenv>/lib/python3.6/site-packages/pytext/main.py", line 450, in predict
    predictions = predictor(input)
  File "<myenv>/lib/python3.6/site-packages/pytext/__init__.py", line 74, in <lambda>
    workspace_id, predict_net, new_task.model, input_tensorizers, input
  File "<myenv>/lib/python3.6/site-packages/pytext/__init__.py", line 27, in _predict
    for name, tensorizer in tensorizers.items()
  File "<myenv>/lib/python3.6/site-packages/pytext/__init__.py", line 27, in <dictcomp>
    for name, tensorizer in tensorizers.items()
  File "<myenv>/lib/python3.6/site-packages/pytext/data/tensorizers.py", line 258, in prepare_input
    tokenized_texts, start_idx, end_idx = self._tokenize(row[self.text_column])
KeyError: 'text'```

**Comment by hudeven** [comment]
@deepali-c thanks for reporting this issue. The root cause is: data_processor.py is outdated. It doesn't generate column 'doc_weight' and 'word_weight' in the training data. 

A quick walk-around is to add them manually to each data file(with doc_weight=0.2, word_weight=0.5). e.g. 
awk '{print $0"\011"0.2"\011"0.5}' demo/atis_joint_model/atis.processed.val.csv > demo/atis_joint_model/atis.processed.val.with_weights.csv

I will fix the data_processor.py soon.

**Comment by deepali-c** [comment]
A similar change `raw_text => text` is needed in the `flask_app` example https://pytext.readthedocs.io/en/master/execute_your_first_model.html at the following line:
```
    # Pass the inputs to PyText's prediction API
    result = predictor({"raw_text": text})
```
