### ISSUE TITLE
error during training with pytorch v1.2.0

### ISSUE THREAD

**Issue by deepali-c** [facebookresearch/pytext#937]
## Steps to reproduce
Execute atis example using the steps at  https://pytext.readthedocs.io/en/master/atis_tutorial.html
`pytext train < sample_config.json`

## Observed Results
```
=== Saving model to: /tmp/model.pt
Saving pytorch model to: /tmp/model.pt
Get numberized rows from cache in stage: Stage.TRAIN
Exporting metrics
<myenv>lib/python3.6/site-packages/torch/nn/modules/module.py:545: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  result = self._slow_forward(*input, **kwargs)
Only tensors or tuples of tensors can be output from traced functions (getOutput at <mydir>conda-bld/pytorch-base_1566252335113/work/torch/csrc/jit/tracer.cpp:208)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xbc (0x7fff48d5b6ac in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: torch::jit::tracer::TracingState::getOutput(c10::IValue const&) + 0x410 (0x7fff4c91fd30 in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #2: torch::jit::tracer::exit(std::vector<c10::IValue, std::allocator<c10::IValue> > const&) + 0x64 (0x7fff4c9200f4 in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #3: <unknown function> + 0x61fdc4 (0x7ffeaf18fdc4 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6401b0 (0x7ffeaf1b01b0 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x23d114 (0x7ffeaedad114 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: _PyCFunction_FastCallDict + 0x1fc (0x13c264dfc in <myenv>bin/python)
frame #7: _PyCFunction_FastCallKeywords + 0x24 (0x13c2b02c4 in <myenv>bin/python)
frame #8: _PyObject_FastCallKeywords + 0x168 (0x13c3449d8 in <myenv>bin/python)
frame #9: <unknown function> + 0x1be390 (0x13c34e390 in <myenv>bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #11: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #12: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #13: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #14: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #16: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #17: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #18: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #19: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #21: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #22: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #23: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #24: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #26: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #27: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #28: _PyFunction_FastCallDict + 0x4dc (0x13c344eec in <myenv>bin/python)
frame #29: _PyObject_FastCallDict + 0x2fc (0x13c26531c in <myenv>bin/python)
frame #30: _PyObject_Call_Prepend + 0x88 (0x13c26e2d8 in <myenv>bin/python)
frame #31: <unknown function> + 0xde404 (0x13c26e404 in <myenv>bin/python)
frame #32: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)
frame #34: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #35: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #36: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #37: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #39: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #40: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #41: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #42: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #44: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #45: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #46: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #47: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #49: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #50: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #51: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #52: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #53: _PyEval_EvalFrameDefault + 0x175c (0x13c38acec in <myenv>bin/python)
frame #54: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #55: PyEval_EvalCodeEx + 0x364 (0x13c345374 in <myenv>bin/python)
frame #56: <unknown function> + 0x1b70f4 (0x13c3470f4 in <myenv>bin/python)
frame #57: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #58: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)
frame #59: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #60: PyEval_EvalCodeEx + 0x364 (0x13c345374 in <myenv>bin/python)
frame #61: <unknown function> + 0x1b70f4 (0x13c3470f4 in <myenv>bin/python)
frame #62: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #63: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)

Error occurs, No graph saved
WARNING: Unable to export neural network graph to TensorBoard.
Traceback (most recent call last):
  File "<myenv>lib/python3.6/site-packages/pytext/metric_reporters/channel.py", line 287, in export
    self.summary_writer.add_graph(model, input_to_model, **kwargs)
  File "<myenv>lib/python3.6/site-packages/torch/utils/tensorboard/writer.py", line 648, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "<myenv>lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 234, in graph
    raise e
  File "<myenv>lib/python3.6/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 229, in graph
    trace = torch.jit.trace(model, args)
  File "<myenv>lib/python3.6/site-packages/torch/jit/__init__.py", line 772, in trace
    check_tolerance, _force_outplace, _module_class)
  File "<myenv>lib/python3.6/site-packages/torch/jit/__init__.py", line 904, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
RuntimeError: Only tensors or tuples of tensors can be output from traced functions (getOutput at <mydir>/conda-bld/pytorch-base_1566252335113/work/torch/csrc/jit/tracer.cpp:208)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xbc (0x7fff48d5b6ac in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libc10.so)
frame #1: torch::jit::tracer::TracingState::getOutput(c10::IValue const&) + 0x410 (0x7fff4c91fd30 in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #2: torch::jit::tracer::exit(std::vector<c10::IValue, std::allocator<c10::IValue> > const&) + 0x64 (0x7fff4c9200f4 in <myenv>lib/python3.6/site-packages/caffe2/python/../../torch/lib/libtorch.so)
frame #3: <unknown function> + 0x61fdc4 (0x7ffeaf18fdc4 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6401b0 (0x7ffeaf1b01b0 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x23d114 (0x7ffeaedad114 in <myenv>lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #6: _PyCFunction_FastCallDict + 0x1fc (0x13c264dfc in <myenv>bin/python)
frame #7: _PyCFunction_FastCallKeywords + 0x24 (0x13c2b02c4 in <myenv>bin/python)
frame #8: _PyObject_FastCallKeywords + 0x168 (0x13c3449d8 in <myenv>bin/python)
frame #9: <unknown function> + 0x1be390 (0x13c34e390 in <myenv>bin/python)
frame #10: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #11: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #12: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #13: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #14: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #15: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #16: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #17: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #18: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #19: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #20: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #21: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #22: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #23: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #24: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #25: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #26: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #27: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #28: _PyFunction_FastCallDict + 0x4dc (0x13c344eec in <myenv>bin/python)
frame #29: _PyObject_FastCallDict + 0x2fc (0x13c26531c in <myenv>bin/python)
frame #30: _PyObject_Call_Prepend + 0x88 (0x13c26e2d8 in <myenv>bin/python)
frame #31: <unknown function> + 0xde404 (0x13c26e404 in <myenv>bin/python)
frame #32: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #33: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)
frame #34: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #35: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #36: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #37: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #38: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #39: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #40: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #41: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #42: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #43: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #44: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #45: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #46: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #47: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #48: _PyEval_EvalFrameDefault + 0x604 (0x13c389b94 in <myenv>bin/python)
frame #49: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #50: <unknown function> + 0x1b2628 (0x13c342628 in <myenv>bin/python)
frame #51: <unknown function> + 0x1b4294 (0x13c344294 in <myenv>bin/python)
frame #52: <unknown function> + 0x1be2cc (0x13c34e2cc in <myenv>bin/python)
frame #53: _PyEval_EvalFrameDefault + 0x175c (0x13c38acec in <myenv>bin/python)
frame #54: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #55: PyEval_EvalCodeEx + 0x364 (0x13c345374 in <myenv>bin/python)
frame #56: <unknown function> + 0x1b70f4 (0x13c3470f4 in <myenv>bin/python)
frame #57: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #58: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)
frame #59: PyEval_EvalFrameEx + 0x34 (0x13c242d94 in <myenv>bin/python)
frame #60: PyEval_EvalCodeEx + 0x364 (0x13c345374 in <myenv>bin/python)
frame #61: <unknown function> + 0x1b70f4 (0x13c3470f4 in <myenv>bin/python)
frame #62: PyObject_Call + 0x74 (0x13c264a84 in <myenv>bin/python)
frame #63: _PyEval_EvalFrameDefault + 0x22c8 (0x13c38b858 in <myenv>bin/python)
```
  
## Expected Results
The training should succeed without errors.

**Comment by deepali-c** [comment]
Yes, in my case too training completes.

**Comment by snisarg** [comment]
This is a TensorBoard warning. I'm not entirely sure if the work we're doing on TensorBoard will fix this, but let's go back to this in case the error persists. I'm hoping updates will fix it.
